# Model fitting on a fixed dataset (mtcars is bundled in both engines).
fit <- lm(mpg ~ wt + hp, data = mtcars)
co <- coef(fit)
cat("lm.intercept=", co[[1]], "\n", sep = "")
cat("lm.wt=", co[[2]], "\n", sep = "")
cat("lm.hp=", co[[3]], "\n", sep = "")
s <- summary(fit)
cat("lm.r2=", s$r.squared, "\n", sep = "")
cat("lm.adjr2=", s$adj.r.squared, "\n", sep = "")
r <- residuals(fit)
cat("lm.res.sum=", sum(r * r), "\n", sep = "")
p <- predict(fit)
cat("lm.pred1=", p[[1]], "\n", sep = "")
g <- glm(am ~ wt, data = mtcars, family = binomial)
gc <- coef(g)
cat("glm.intercept=", gc[[1]], "\n", sep = "")
cat("glm.wt=", gc[[2]], "\n", sep = "")
cat("glm.dev=", deviance(g), "\n", sep = "")
