# Deterministic statistics on fixed data (no RNG).
x <- c(2.1, 4.7, 1.3, 8.9, 5.5, 3.2, 7.8, 6.4, 0.9, 9.1)
y <- c(1.0, 3.5, 2.2, 7.1, 4.9, 2.8, 6.6, 5.9, 1.4, 8.3)
cat("mean=", mean(x), "\n", sep = "")
cat("median=", median(x), "\n", sep = "")
cat("sd=", sd(x), "\n", sep = "")
cat("var=", var(x), "\n", sep = "")
cat("cor=", cor(x, y), "\n", sep = "")
cat("cov=", cov(x, y), "\n", sep = "")
cat("min=", min(x), "\n", sep = "")
cat("max=", max(x), "\n", sep = "")
cat("range.diff=", diff(range(x)), "\n", sep = "")
cat("sum=", sum(x), "\n", sep = "")
cat("prod.small=", prod(x[1:4]), "\n", sep = "")
cat("cumsum.last=", cumsum(x)[10], "\n", sep = "")
cat("cummax.last=", cummax(x)[10], "\n", sep = "")
cat("q25=", quantile(x, 0.25)[[1]], "\n", sep = "")
cat("q75=", quantile(x, 0.75)[[1]], "\n", sep = "")
cat("which.max=", which.max(x), "\n", sep = "")
cat("which.min=", which.min(x), "\n", sep = "")
cat("rank.first=", rank(x)[1], "\n", sep = "")
cat("order.first=", order(x)[1], "\n", sep = "")
cat("scale.e1=", scale(x)[1], "\n", sep = "")
