# String manipulation battery.
s <- c("Hello World", "foo bar", "R2 engine")
cat("nchar=", paste(nchar(s), collapse = ","), "\n", sep = "")
cat("toupper=", toupper(s[2]), "\n", sep = "")
cat("tolower=", tolower(s[1]), "\n", sep = "")
cat("substr=", substr(s[1], 1, 5), "\n", sep = "")
cat("paste=", paste(s[1], s[2], sep = "-"), "\n", sep = "")
cat("paste0=", paste0("x", 1:3, collapse = ","), "\n", sep = "")
cat("sub=", sub("o", "0", s[1]), "\n", sep = "")
cat("gsub=", gsub("o", "0", s[2]), "\n", sep = "")
cat("grepl=", paste(as.integer(grepl("o", s)), collapse = ","), "\n", sep = "")
cat("grep=", paste(grep("e", s), collapse = ","), "\n", sep = "")
cat("strsplit=", strsplit(s[1], " ")[[1]][2], "\n", sep = "")
cat("sprintf.f=", sprintf("%.3f", 3.14159), "\n", sep = "")
cat("sprintf.d=", sprintf("%05d", 42), "\n", sep = "")
cat("sprintf.s=", sprintf("%s has %d", "x", 7), "\n", sep = "")
cat("trimws=", trimws("  pad  "), "\n", sep = "")
cat("regexpr=", regexpr("World", s[1])[1], "\n", sep = "")
cat("startsWith=", if (startsWith(s[1], "Hell")) 1 else 0, "\n", sep = "")
cat("rev.str=", paste(rev(strsplit("abc", "")[[1]]), collapse = ""), "\n", sep = "")
